sudo: false
language: node_js
node_js:
- 9

install:
- npm install
- npm run build
script:
- npm run lint
- npm run test-coverage
- npm run coveralls-coverage
- npm run test-coverage-report && npm run test-coverage-check
